# BUILD
FROM node:20 AS build

WORKDIR /app

COPY .env .env

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# RUN
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
