FROM nginx:alpine

COPY ssl/domain.cert.pem /etc/ssl/domain.cert.pem
COPY ssl/private.key.pem /etc/private.key.pem

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]